let handler = async(m, { conn, usedPrefix, command, text }) => {
let fdoc = {quoted:{key : {participant : '0@s.whatsapp.net'},message: {documentMessage: {title: `${command}`}}}}

if (!text) throw `Gunakan contoh ${usedPrefix + command} hello`

	const sections = [
    {
	title: "Theme",
	rows: [
	{title: "3d-effect", rowId: usedPrefix + 'textprox 3d-effect ' + text},
{title: "3d-rubystone", rowId: usedPrefix + 'textprox 3d-rubystone ' + text},
{title: "3d-text-sub-zombie", rowId: usedPrefix + 'textprox 3d-text-sub-zombie ' + text},
{title: "3dengraved", rowId: usedPrefix + 'textprox 3dengraved ' + text},
{title: "3dgolden", rowId: usedPrefix + 'textprox 3dgolden ' + text},
{title: "3dgradient", rowId: usedPrefix + 'textprox 3dgradient ' + text},
{title: "3dlove", rowId: usedPrefix + 'textprox 3dlove ' + text},
{title: "3dluxury", rowId: usedPrefix + 'textprox 3dluxury ' + text},
{title: "3dneonlight", rowId: usedPrefix + 'textprox 3dneonlight ' + text},
{title: "3dpapercut", rowId: usedPrefix + 'textprox 3dpapercut ' + text},
{title: "3drainbow", rowId: usedPrefix + 'textprox 3drainbow ' + text},
{title: "3drealistic", rowId: usedPrefix + 'textprox 3drealistic ' + text},
{title: "3dscifi", rowId: usedPrefix + 'textprox 3dscifi ' + text},
{title: "3dtext-effect", rowId: usedPrefix + 'textprox 3dtext-effect ' + text},
{title: "3dunderwater", rowId: usedPrefix + 'textprox 3dunderwater ' + text},
{title: "3dwaterpipe", rowId: usedPrefix + 'textprox 3dwaterpipe ' + text},
{title: "1917-style", rowId: usedPrefix + 'textprox 1917-style ' + text},
{title: "alice-league-of-kings", rowId: usedPrefix + 'textprox alice-league-of-kings ' + text},
{title: "angel-wing-galaxy", rowId: usedPrefix + 'textprox angel-wing-galaxy ' + text},
{title: "anubis", rowId: usedPrefix + 'textprox anubis ' + text},
{title: "arch-crossfire", rowId: usedPrefix + 'textprox arch-crossfire ' + text},
{title: "art-shader", rowId: usedPrefix + 'textprox art-shader ' + text},
{title: "assassins-creed", rowId: usedPrefix + 'textprox assassins-creed ' + text},
{title: "azzenka-league-of-kings", rowId: usedPrefix + 'textprox azzenka-league-of-kings ' + text},
{title: "bearlogo", rowId: usedPrefix + 'textprox bearlogo ' + text},
{title: "bg-crossfire", rowId: usedPrefix + 'textprox bg-crossfire ' + text},
{title: "birthday-cake", rowId: usedPrefix + 'textprox birthday-cake ' + text},
{title: "birthday-cards", rowId: usedPrefix + 'textprox birthday-cards ' + text},
{title: "birthday-greeting", rowId: usedPrefix + 'textprox birthday-greeting ' + text},
{title: "birthday-roses", rowId: usedPrefix + 'textprox birthday-roses ' + text},
{title: "black-metal", rowId: usedPrefix + 'textprox black-metal ' + text},
{title: "blackpink", rowId: usedPrefix + 'textprox blackpink ' + text},
{title: "blood-frosted", rowId: usedPrefix + 'textprox blood-frosted ' + text},
{title: "blood-text", rowId: usedPrefix + 'textprox blood-text ' + text},
{title: "blue-effect", rowId: usedPrefix + 'textprox blue-effect ' + text},
{title: "blue-glitter", rowId: usedPrefix + 'textprox blue-glitter ' + text},
{title: "brickwall", rowId: usedPrefix + 'textprox brickwall ' + text},
{title: "brokentext", rowId: usedPrefix + 'textprox brokentext ' + text},
{title: "bubble-effect", rowId: usedPrefix + 'textprox bubble-effect ' + text},
{title: "bulb-effect", rowId: usedPrefix + 'textprox bulb-effect ' + text},
{title: "circuit", rowId: usedPrefix + 'textprox circuit ' + text},
{title: "color-fireworks", rowId: usedPrefix + 'textprox color-fireworks ' + text},
{title: "cool-metal", rowId: usedPrefix + 'textprox cool-metal ' + text},
{title: "dark-gold-metal", rowId: usedPrefix + 'textprox dark-gold-metal ' + text},
{title: "decorated-cookie", rowId: usedPrefix + 'textprox decorated-cookie ' + text},
{title: "deluxe-gold", rowId: usedPrefix + 'textprox deluxe-gold ' + text},
{title: "deluxe-silver", rowId: usedPrefix + 'textprox deluxe-silver ' + text},
{title: "dinamo", rowId: usedPrefix + 'textprox dinamo ' + text},
{title: "double-exposure", rowId: usedPrefix + 'textprox double-exposure ' + text},
{title: "dragon-fire", rowId: usedPrefix + 'textprox dragon-fire ' + text},
{title: "eroded-metal", rowId: usedPrefix + 'textprox eroded-metal ' + text},
{title: "fabric-text", rowId: usedPrefix + 'textprox fabric-text ' + text},
{title: "firework", rowId: usedPrefix + 'textprox firework ' + text},
{title: "fox-crossfire", rowId: usedPrefix + 'textprox fox-crossfire ' + text},
{title: "fun-certify1", rowId: usedPrefix + 'textprox fun-certify1 ' + text},
{title: "fun-certify2", rowId: usedPrefix + 'textprox fun-certify2 ' + text},
{title: "futuristic", rowId: usedPrefix + 'textprox futuristic ' + text},
{title: "galaxy-angel", rowId: usedPrefix + 'textprox galaxy-angel ' + text},
{title: "galaxy-effect", rowId: usedPrefix + 'textprox galaxy-effect ' + text},
{title: "galaxy-effect2", rowId: usedPrefix + 'textprox galaxy-effect2 ' + text},
{title: "galaxy-text", rowId: usedPrefix + 'textprox galaxy-text ' + text},
{title: "galaxy-text-3", rowId: usedPrefix + 'textprox galaxy-text-3 ' + text},
{title: "gankk-league-of-kings", rowId: usedPrefix + 'textprox gankk-league-of-kings ' + text},
{title: "gemstone", rowId: usedPrefix + 'textprox gemstone ' + text},
{title: "genji-overwatch", rowId: usedPrefix + 'textprox genji-overwatch ' + text},
{title: "glossy", rowId: usedPrefix + 'textprox glossy ' + text},
{title: "glossy-bluemetal", rowId: usedPrefix + 'textprox glossy-bluemetal ' + text},
{title: "glossy-carbon", rowId: usedPrefix + 'textprox glossy-carbon ' + text},
{title: "glossy-chrome", rowId: usedPrefix + 'textprox glossy-chrome ' + text},
{title: "gold-avenger", rowId: usedPrefix + 'textprox gold-avenger ' + text},
{title: "gold-barcar", rowId: usedPrefix + 'textprox gold-barcar ' + text},
{title: "gold-batman", rowId: usedPrefix + 'textprox gold-batman ' + text},
{title: "gold-bird2", rowId: usedPrefix + 'textprox gold-bird2 ' + text},
{title: "gold-eagle", rowId: usedPrefix + 'textprox gold-eagle ' + text},
{title: "gold-effect", rowId: usedPrefix + 'textprox gold-effect ' + text},
{title: "gold-fox", rowId: usedPrefix + 'textprox gold-fox ' + text},
{title: "gold-glitter", rowId: usedPrefix + 'textprox gold-glitter ' + text},
{title: "gold-lion", rowId: usedPrefix + 'textprox gold-lion ' + text},
{title: "gold-lion2", rowId: usedPrefix + 'textprox gold-lion2 ' + text},
{title: "gold-star", rowId: usedPrefix + 'textprox gold-star ' + text},
{title: "gold-tiger", rowId: usedPrefix + 'textprox gold-tiger ' + text},
{title: "golden-letter", rowId: usedPrefix + 'textprox golden-letter ' + text},
{title: "gr-crossfire", rowId: usedPrefix + 'textprox gr-crossfire ' + text},
{title: "graffiti-color", rowId: usedPrefix + 'textprox graffiti-color ' + text},
{title: "graffiti-text3", rowId: usedPrefix + 'textprox graffiti-text3 ' + text},
{title: "graffiti-text4", rowId: usedPrefix + 'textprox graffiti-text4 ' + text},
{title: "graffiti-text5", rowId: usedPrefix + 'textprox graffiti-text5 ' + text},
{title: "graffiti-text8", rowId: usedPrefix + 'textprox graffiti-text8 ' + text},
{title: "graffititext", rowId: usedPrefix + 'textprox graffititext ' + text},
{title: "green-brush", rowId: usedPrefix + 'textprox green-brush ' + text},
{title: "greenhorror", rowId: usedPrefix + 'textprox greenhorror ' + text},
{title: "halloween-fire", rowId: usedPrefix + 'textprox halloween-fire ' + text},
{title: "hanzo-overwatch", rowId: usedPrefix + 'textprox hanzo-overwatch ' + text},
{title: "heart-birthday", rowId: usedPrefix + 'textprox heart-birthday ' + text},
{title: "heart-cups", rowId: usedPrefix + 'textprox heart-cups ' + text},
{title: "heart-flashlight", rowId: usedPrefix + 'textprox heart-flashlight ' + text},
{title: "hero3-crossfire", rowId: usedPrefix + 'textprox hero3-crossfire ' + text},
{title: "holographic", rowId: usedPrefix + 'textprox holographic ' + text},
{title: "ledtext", rowId: usedPrefix + 'textprox ledtext ' + text},
{title: "lend-text", rowId: usedPrefix + 'textprox lend-text ' + text},
{title: "light-text", rowId: usedPrefix + 'textprox light-text ' + text},
{title: "logo-galaxy", rowId: usedPrefix + 'textprox logo-galaxy ' + text},
{title: "lol-ahri", rowId: usedPrefix + 'textprox lol-ahri ' + text},
{title: "lol-caitlyn", rowId: usedPrefix + 'textprox lol-caitlyn ' + text},
{title: "lol-draven", rowId: usedPrefix + 'textprox lol-draven ' + text},
{title: "lol-ezreal-and-shen", rowId: usedPrefix + 'textprox lol-ezreal-and-shen ' + text},
{title: "lol-fiora", rowId: usedPrefix + 'textprox lol-fiora ' + text},
{title: "lol-fizz", rowId: usedPrefix + 'textprox lol-fizz ' + text},
{title: "lol-garen", rowId: usedPrefix + 'textprox lol-garen ' + text},
{title: "lol-graves", rowId: usedPrefix + 'textprox lol-graves ' + text},
{title: "lol-jhin", rowId: usedPrefix + 'textprox lol-jhin ' + text},
{title: "lol-jinx", rowId: usedPrefix + 'textprox lol-jinx ' + text},
{title: "lol-kalista", rowId: usedPrefix + 'textprox lol-kalista ' + text},
{title: "lol-khazix", rowId: usedPrefix + 'textprox lol-khazix ' + text},
{title: "lol-kogmaw", rowId: usedPrefix + 'textprox lol-kogmaw ' + text},
{title: "lol-leesin", rowId: usedPrefix + 'textprox lol-leesin ' + text},
{title: "lol-lux", rowId: usedPrefix + 'textprox lol-lux ' + text},
{title: "lol-master-yi", rowId: usedPrefix + 'textprox lol-master-yi ' + text},
{title: "lol-miss-fortune", rowId: usedPrefix + 'textprox lol-miss-fortune ' + text},
{title: "lol-nidalee", rowId: usedPrefix + 'textprox lol-nidalee ' + text},
{title: "lol-quinn", rowId: usedPrefix + 'textprox lol-quinn ' + text},
{title: "lol-rengar", rowId: usedPrefix + 'textprox lol-rengar ' + text},
{title: "lol-riven", rowId: usedPrefix + 'textprox lol-riven ' + text},
{title: "lol-sona", rowId: usedPrefix + 'textprox lol-sona ' + text},
{title: "lol-talon", rowId: usedPrefix + 'textprox lol-talon ' + text},
{title: "lol-thresh", rowId: usedPrefix + 'textprox lol-thresh ' + text},
{title: "lol-vayne", rowId: usedPrefix + 'textprox lol-vayne ' + text},
{title: "lol-wukong", rowId: usedPrefix + 'textprox lol-wukong ' + text},
{title: "lol-yasuo", rowId: usedPrefix + 'textprox lol-yasuo ' + text},
{title: "lol-zed", rowId: usedPrefix + 'textprox lol-zed ' + text},
{title: "machines-effect", rowId: usedPrefix + 'textprox machines-effect ' + text},
{title: "magic-text", rowId: usedPrefix + 'textprox magic-text ' + text},
{title: "magmatext", rowId: usedPrefix + 'textprox magmatext ' + text},
{title: "matrix-text", rowId: usedPrefix + 'textprox matrix-text ' + text},
{title: "mei-overwatch", rowId: usedPrefix + 'textprox mei-overwatch ' + text},
{title: "mercy-overwatch", rowId: usedPrefix + 'textprox mercy-overwatch ' + text},
{title: "metal-avenger", rowId: usedPrefix + 'textprox metal-avenger ' + text},
{title: "metal-headshot", rowId: usedPrefix + 'textprox metal-headshot ' + text},
{title: "metal-lion-2", rowId: usedPrefix + 'textprox metal-lion-2 ' + text},
{title: "metal-real-madrid", rowId: usedPrefix + 'textprox metal-real-madrid ' + text},
{title: "metal-star", rowId: usedPrefix + 'textprox metal-star ' + text},
{title: "metal-superman", rowId: usedPrefix + 'textprox metal-superman ' + text},
{title: "metal-text-effect", rowId: usedPrefix + 'textprox metal-text-effect ' + text},
{title: "metal-wolf-2", rowId: usedPrefix + 'textprox metal-wolf-2 ' + text},
{title: "metalic", rowId: usedPrefix + 'textprox metalic ' + text},
{title: "metallic-letter", rowId: usedPrefix + 'textprox metallic-letter ' + text},
{title: "mganga-league-of-kings", rowId: usedPrefix + 'textprox mganga-league-of-kings ' + text},
{title: "miniontext", rowId: usedPrefix + 'textprox miniontext ' + text},
{title: "modern-gold-3", rowId: usedPrefix + 'textprox modern-gold-3 ' + text},
{title: "modern-gold-4", rowId: usedPrefix + 'textprox modern-gold-4 ' + text},
{title: "modern-gold-5-pro", rowId: usedPrefix + 'textprox modern-gold-5-pro ' + text},
{title: "modern-gold-green", rowId: usedPrefix + 'textprox modern-gold-green ' + text},
{title: "modern-gold-purple", rowId: usedPrefix + 'textprox modern-gold-purple ' + text},
{title: "modern-gold-red", rowId: usedPrefix + 'textprox modern-gold-red ' + text},
{title: "modern-gold-sliver", rowId: usedPrefix + 'textprox modern-gold-sliver ' + text},
{title: "modern-goldred", rowId: usedPrefix + 'textprox modern-goldred ' + text},
{title: "name-on-hot-air-ballon", rowId: usedPrefix + 'textprox name-on-hot-air-ballon ' + text},
{title: "neon", rowId: usedPrefix + 'textprox neon ' + text},
{title: "neon-2", rowId: usedPrefix + 'textprox neon-2 ' + text},
{title: "neon-brightblue", rowId: usedPrefix + 'textprox neon-brightblue ' + text},
{title: "neon-effects", rowId: usedPrefix + 'textprox neon-effects ' + text},
{title: "neon-light-galaxy", rowId: usedPrefix + 'textprox neon-light-galaxy ' + text},
{title: "neon-satin", rowId: usedPrefix + 'textprox neon-satin ' + text},
{title: "neondevil", rowId: usedPrefix + 'textprox neondevil ' + text},
{title: "neonlight", rowId: usedPrefix + 'textprox neonlight ' + text},
{title: "neontext-light", rowId: usedPrefix + 'textprox neontext-light ' + text},
{title: "paper-cut", rowId: usedPrefix + 'textprox paper-cut ' + text},
{title: "paperart", rowId: usedPrefix + 'textprox paperart ' + text},
{title: "rainbow-effect", rowId: usedPrefix + 'textprox rainbow-effect ' + text},
{title: "reaper-overwatch", rowId: usedPrefix + 'textprox reaper-overwatch ' + text},
{title: "red-birthdaycake", rowId: usedPrefix + 'textprox red-birthdaycake ' + text},
{title: "redhot-metal", rowId: usedPrefix + 'textprox redhot-metal ' + text},
{title: "resht-league-of-kings", rowId: usedPrefix + 'textprox resht-league-of-kings ' + text},
{title: "science", rowId: usedPrefix + 'textprox science ' + text},
{title: "sfg-crossfire", rowId: usedPrefix + 'textprox sfg-crossfire ' + text},
{title: "skeleton", rowId: usedPrefix + 'textprox skeleton ' + text},
{title: "sketch", rowId: usedPrefix + 'textprox sketch ' + text},
{title: "snowtext", rowId: usedPrefix + 'textprox snowtext ' + text},
{title: "soldier-overwatch", rowId: usedPrefix + 'textprox soldier-overwatch ' + text},
{title: "status-life", rowId: usedPrefix + 'textprox status-life ' + text},
{title: "status-life-1", rowId: usedPrefix + 'textprox status-life-1 ' + text},
{title: "status-life-2", rowId: usedPrefix + 'textprox status-life-2 ' + text},
{title: "status-love", rowId: usedPrefix + 'textprox status-love ' + text},
{title: "status-mood", rowId: usedPrefix + 'textprox status-mood ' + text},
{title: "status-mood-1", rowId: usedPrefix + 'textprox status-mood-1 ' + text},
{title: "status-mood-2", rowId: usedPrefix + 'textprox status-mood-2 ' + text},
{title: "status-mood-3", rowId: usedPrefix + 'textprox status-mood-3 ' + text},
{title: "sunlight-shadow", rowId: usedPrefix + 'textprox sunlight-shadow ' + text},
{title: "swat-crossfire", rowId: usedPrefix + 'textprox swat-crossfire ' + text},
{title: "tattoo-dragon", rowId: usedPrefix + 'textprox tattoo-dragon ' + text},
{title: "text-birthdaycake", rowId: usedPrefix + 'textprox text-birthdaycake ' + text},
{title: "text-birthdaycake2", rowId: usedPrefix + 'textprox text-birthdaycake2 ' + text},
{title: "thundertext", rowId: usedPrefix + 'textprox thundertext ' + text},
{title: "torbjornplate-overwatch", rowId: usedPrefix + 'textprox torbjornplate-overwatch ' + text},
{title: "transformer", rowId: usedPrefix + 'textprox transformer ' + text},
{title: "typography-autumn", rowId: usedPrefix + 'textprox typography-autumn ' + text},
{title: "typography-leaves", rowId: usedPrefix + 'textprox typography-leaves ' + text},
{title: "typography-maker1", rowId: usedPrefix + 'textprox typography-maker1 ' + text},
{title: "violet-league-of-kings", rowId: usedPrefix + 'textprox violet-league-of-kings ' + text},
{title: "water-3d", rowId: usedPrefix + 'textprox water-3d ' + text},
{title: "water-effect", rowId: usedPrefix + 'textprox water-effect ' + text},
{title: "watercolor", rowId: usedPrefix + 'textprox watercolor ' + text},
{title: "wedding-silver", rowId: usedPrefix + 'textprox wedding-silver ' + text},
{title: "wetglass", rowId: usedPrefix + 'textprox wetglass ' + text},
{title: "wings-effect", rowId: usedPrefix + 'textprox wings-effect ' + text},
{title: "wishes-birthdaycake", rowId: usedPrefix + 'textprox wishes-birthdaycake ' + text},
{title: "word-greenfireworks", rowId: usedPrefix + 'textprox word-greenfireworks ' + text},
{title: "word-leaves", rowId: usedPrefix + 'textprox word-leaves ' + text}
	]
    }
]

const listMessage = {
  text: `⚡ Silakan pilih tema di tombol di bawah...\n*Teks yang anda kirim:* ${text}\n\nKetik ulang *${usedPrefix + command}* teks anda untuk mengubah teks lagi`,
  footer: global.wm,
  title: `⎔───「 ${command} 」───⎔`,
  buttonText: `☂️ Tema Disini ☂️`,
  sections
}
conn.sendMessage(m.chat, listMessage, fdoc)
}
handler.help = ['maker9 hello']
handler.tags = ['maker']
handler.command = /^(maker9)$/i
export default handler